-- Maltese localities, used as the only allowed source for property addresses.
-- Source: National Statistics Office Malta + Identity Malta. Includes Malta + Gozo.
-- Spec §5: dropdown only, no free text.

INSERT INTO public.maltese_localities (name_en, name_mt) VALUES
  ('Attard',          'Attard'),
  ('Balzan',          'Balzan'),
  ('Birgu',           'Birgu (Vittoriosa)'),
  ('Birkirkara',      'Birkirkara'),
  ('Birzebbuga',      'Birżebbuġa'),
  ('Bormla',          'Bormla (Cospicua)'),
  ('Dingli',          'Ħad-Dingli'),
  ('Fgura',           'Fgura'),
  ('Floriana',        'Floriana'),
  ('Fontana',         'Fontana'),
  ('Gharb',           'Għarb'),
  ('Gharghur',        'Għargħur'),
  ('Ghasri',          'Għasri'),
  ('Ghaxaq',          'Għaxaq'),
  ('Gudja',           'Gudja'),
  ('Gzira',           'Gżira'),
  ('Hamrun',          'Ħamrun'),
  ('Iklin',           'L-Iklin'),
  ('Isla',            'Isla (Senglea)'),
  ('Kalkara',         'Kalkara'),
  ('Kercem',          'Kerċem'),
  ('Kirkop',          'Ħal Kirkop'),
  ('Lija',            'Lija'),
  ('Luqa',            'Ħal Luqa'),
  ('Marsa',           'Marsa'),
  ('Marsaskala',      'Marsaskala'),
  ('Marsaxlokk',      'Marsaxlokk'),
  ('Mdina',           'L-Imdina'),
  ('Mellieha',        'Il-Mellieħa'),
  ('Mgarr',           'L-Imġarr'),
  ('Mosta',           'Il-Mosta'),
  ('Mqabba',          'Ħal Mqabba'),
  ('Msida',           'L-Imsida'),
  ('Mtarfa',          'L-Imtarfa'),
  ('Munxar',          'Munxar'),
  ('Nadur',           'In-Nadur'),
  ('Naxxar',          'In-Naxxar'),
  ('Paola',           'Raħal Ġdid (Paola)'),
  ('Pembroke',        'Pembroke'),
  ('Pieta',           'Tal-Pietà'),
  ('Qala',            'Il-Qala'),
  ('Qormi',           'Ħal Qormi'),
  ('Qrendi',          'Il-Qrendi'),
  ('Rabat (Gozo)',    'Ir-Rabat (Għawdex)'),
  ('Rabat (Malta)',   'Ir-Rabat (Malta)'),
  ('Safi',            'Ħal Safi'),
  ('San Giljan',      'San Ġiljan (St Julian''s)'),
  ('San Gwann',       'San Ġwann'),
  ('San Lawrenz',     'San Lawrenz'),
  ('San Pawl il-Bahar','San Pawl il-Baħar (St Paul''s Bay)'),
  ('Sannat',          'Ta'' Sannat'),
  ('Santa Lucija',    'Santa Luċija'),
  ('Santa Venera',    'Santa Venera'),
  ('Siggiewi',        'Is-Siġġiewi'),
  ('Sliema',          'Tas-Sliema'),
  ('Swieqi',          'Is-Swieqi'),
  ('Ta'' Xbiex',      'Ta'' Xbiex'),
  ('Tarxien',         'Ħal Tarxien'),
  ('Valletta',        'Il-Belt Valletta'),
  ('Xaghra',          'Ix-Xagħra'),
  ('Xewkija',         'Ix-Xewkija'),
  ('Xghajra',         'Ix-Xgħajra'),
  ('Zabbar',          'Ħaż-Żabbar'),
  ('Zebbug (Gozo)',   'Iż-Żebbuġ (Għawdex)'),
  ('Zebbug (Malta)',  'Ħaż-Żebbuġ (Malta)'),
  ('Zejtun',          'Iż-Żejtun'),
  ('Zurrieq',         'Iż-Żurrieq')
ON CONFLICT (name_en) DO NOTHING;
